export enum GetCvActions {
  GET_CV_CALLER = 'GET_CV_CALLER',
  GET_CV_STARTED = 'GET_CV_STARTED',
  GET_CV_FAILED = 'GET_CV_FAILED',
  GET_CV_SUCCESS = 'GET_CV_SUCCESS',
  GET_CV_DEFAULT = 'GET_CV_DEFAULT',
}

export enum GetAllJobs {
  GET_JOBS__CALLER = 'GET_JOBS__CALLER',
  GET_JOBS__STARTED = 'GET_JOBS__STARTED',
  GET_JOBS__FAILED = 'GET_JOBS__FAILED',
  GET_JOBS__SUCCESS = 'GET_JOBS__SUCCESS',
  GET_JOBS__DEFAULT = 'GET_JOBS__DEFAULT',
}

export enum AddCredentialsAction {
  ADD_CREDENTIALS_CALLER = 'ADD_CREDENTIALS_CALLER',
  ADD_CREDENTIALS_STARTED = 'ADD_CREDENTIALS_STARTED',
  ADD_CREDENTIALS_DEFAULT = 'ADD_CREDENTIALS_DEFAULT',
  ADD_CREDENTIALS_FAILED = 'ADD_CREDENTIALS_FAILED',
  ADD_CREDENTIALS_SUCCESS = 'ADD_CREDENTIALS_SUCCESS',
}

export enum DeleteCredentialAction {
  DELETE_CREDENTIALS_CALLER = 'DELETE_CREDENTIALS_CALLER',
  DELETE_CREDENTIALS_STARTED = 'DELETE_CREDENTIALS_STARTED',
  DELETE_CREDENTIALS_DEFAULT = 'DELETE_CREDENTIALS_DEFAULT',
  DELETE_CREDENTIALS_FAILED = 'DELETE_CREDENTIALS_FAILED',
  DELETE_CREDENTIALS_SUCCESS = 'DELETE_CREDENTIALS_SUCCESS',
}

export enum GetSubscription {
  GET_SUBSCRIPTION_CALLER = 'GET_SUBSCRIPTION_CALLER',
  GET_SUBSCRIPTION_STARTED = 'GET_SUBSCRIPTION_STARTED',
  GET_SUBSCRIPTION_FAILED = 'GET_SUBSCRIPTION_FAILED',
  GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS',
  GET_SUBSCRIPTION_DEFAULT = 'GET_SUBSCRIPTION_DEFAULT',
}

export enum SetSubscription {
  SET_SUBSCRIPTION_CALLER = 'SET_SUBSCRIPTION_CALLER',
  SET_SUBSCRIPTION_STARTED = 'SET_SUBSCRIPTION_STARTED',
  SET_SUBSCRIPTION_FAILED = 'SET_SUBSCRIPTION_FAILED',
  SET_SUBSCRIPTION_SUCCESS = 'SET_SUBSCRIPTION_SUCCESS',
  SET_SUBSCRIPTION_DEFAULT = 'SET_SUBSCRIPTION_DEFAULT',
}
