export enum inputAction {
  SET_SIGNUP_FULLNAME_CALLER = "SET-SIGNUP-FULLNAME_CALLER",
  SET_SIGNUP_PASSWORD_CALLER = "SET-SIGNUP-PASSWORD-CALLER",
  SET_SIGNUP_PHONENUMBER_CALLER = "SET-SIGNUP-PHONENUMBER-CALLER",
  SET_LOGIN_PHONENUMBER_CALLER = "SET-LOGIN-PHONENUMBER-CALLER",
  SET_LOGIN_PASSWORD_CALLER = "SET-LOGIN-PASSWORD_CALLER",
  SET_VERIFICATION_CODE_CALLER = "SET-VERIFICATION-CODE-CALLER",
  SET_VERIFY_RESSET_PASSWORD_PHONE_NUMBER_CALLER = "SET_VERIFY_RESSET_PASSWORD_PHONE_NUMBER_CALLER",
  SET_NEW_PASSWORD_CALLER = "SET_NEW_PASSWORD_CALLER",
  SET_CONFIRM_NEW_PASSWORD_CALLER = "SET_CONFIRM_NEW_PASSWORD_CALLER",

  SET_SIGNUP_FULLNAME = "SET-SIGNUP-FULLNAME",
  SET_SIGNUP_PASSWORD = "SET-SIGNUP-PASSWORD",
  SET_SIGNUP_PHONENUMBER = "SET-SIGNUP-PHONENUMBER",
  SET_LOGIN_PHONENUMBER = "SET-LOGIN-PHONENUMBER",
  SET_LOGIN_PASSWORD = "SET-LOGIN-PASSWORD",
  SET_VERIFICATION_CODE = "SET-VERIFICATION-CODE",
  SET_VERIFY_RESSET_PASSWORD_PHONE_NUMBER = "SET_VERIFY_RESSET_PASSWORD_PHONE_NUMBER",
  SET_NEW_PASSWORD = "SET_NEW_PASSWORD",
  SET_CONFIRM_NEW_PASSWORD = "SET_CONFIRM_NEW_PASSWORD",
}

export enum loginAction {
  LOGIN_STARTED = "LOGIN_STARTED",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_CALLER = "LOGIN_CALLER",
  LOGIN_DEFAULT = "LOGIN_DEFAULT",
}

export enum signUpAction {
  SIGNUP_STARTED = "SIGNUP_STARTED",
  SIGNUP_FAILED = "SIGNUP_FAILED",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  SIGNUP_CALLER = "SIGNUP_CALLER",
  SIGNUP_DEFAULT = "SIGNUP_DEFAULT",
}

export enum verifyPin {
  VERIFYING_PIN_STARTED = "VERIFYING_PIN_STARTED",
  VERIFYING_PIN_FAILED = "VERIFYING_PIN_FAILED",
  VERIFYING_PIN_SUCCESS = "VERIFYING_PIN_SUCCESS",
  VERIFYING_PIN_CALLER = "VERIFYING_PIN_CALLER",
  VERIFYING_PIN_DEFAULT = "VERIFYING_PIN_DEFAULT",
}

export enum sendVerificationPin {
  SEND_VERIFICATION_PIN_STARTED = "SEND_VERIFICATION_PIN_STARTED",
  SEND_VERIFICATION_PIN_FAILED = "SEND_VERIFICATION_PIN_FAILED",
  SEND_VERIFICATION_PIN_SUCCESS = "SEND_VERIFICATION_PIN_SUCCESS",
  SEND_VERIFICATION_PIN_CALLER = "SEND_VERIFICATION_PIN_CALLER",
  SEND_VERIFICATION_PIN_DEFAULT = "SEND_VERIFICATION_PIN_DEFAULT",
}

export enum ressetPassword {
  RESSET_PASSWORD_STARTED = "RESSET_PASSWORD_STARTED",
  RESSET_PASSWORD_FAILED = "RESSET_PASSWORD_FAILED",
  RESSET_PASSWORD_SUCCESS = "RESSET_PASSWORD_SUCCESS",
  RESSET_PASSWORD_CALLER = "RESSET_PASSWORD_CALLER",
  RESSET_PASSWORD_DEFAULT = "RESSET_PASSWORD_DEFAULT",
}

export enum LogOut {
  LOGOUT_CALLER = "LOGOUT_CALLER",
  LOGOUT = "LOGOUT",
}
