export enum StepInputAction {
  SET_FIELD_VALUE_CALLER = "SET_FIELD_VALUE_CALLER",
  SET_ERROR_TEXT_CALLER = "SET_ERROR_TEXT_CALLER",
  RESET_SUBMIT_STATUS_CALLER = "RESET-SUBMIT-STATUS-CALLER",
  SET_FIELD_VALUE = "SET_FIELD_VALUE",
  SET_ERROR_TEXT = "SET_ERROR_TEXT",
  RESET_SUBMIT_STATUS = "RESET-SUBMIT-STATUS",
}

export enum SubmitCv {
  SUBMITCV_DEFAULT = "SUBMIT-CV-DEFAULT",
  SUBMITCV_STARTED = "SUMIT-CV-STARTED",
  SUBMITCV_SUCCESS = "SUBMIT-CV-SUCCESS",
  SUBMITCV_FAILED = "SUBMIT-CV-FAILED",
  SUBMITCV_CALLER = "SUBMIT-CV-CALLER",
}
